<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ulangi 6 digit PIN baru Anda_confirmNewPin_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>be402fca-e6d3-4421-b2b8-61aabe08baa2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pin-input-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pin-input-5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1dfdd8c6-969d-4c40-a5e7-0e41d31d3883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cc2e69bb-5fd5-47c2-b7ed-c69525e4aa85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>otp__input_30CvO false</value>
      <webElementGuid>34c4ad47-a09e-44fd-a439-a5a29fe7ccfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pin-input-5</value>
      <webElementGuid>b8c21ce3-3a9a-4f75-ba34-a86f13057d6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirmNewPin</value>
      <webElementGuid>71a3f6f1-08f4-4c3f-900b-3a3b14305dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9.]+</value>
      <webElementGuid>26bd1c1f-5c04-4fb6-9408-477cf9e16843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>e8648376-27a5-428b-9ed1-724126945d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pin-input-5&quot;)</value>
      <webElementGuid>74cbd09d-0aec-49af-b383-9b7e6edf16b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pin-input-5']</value>
      <webElementGuid>a6be024f-d67e-4385-a78c-4ee78a45ac1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div[2]/div/div/div/div[6]/input</value>
      <webElementGuid>59b81f19-901d-42b8-a5a9-1a24927601b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>bb418c99-98f6-4b88-857a-c2e1c5a6cc11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pin-input-5' and @name = 'confirmNewPin' and @type = 'tel']</value>
      <webElementGuid>464c2b91-b31c-46c1-9ad0-caf6cee77666</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
