<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ke_otp</name>
   <tag></tag>
   <elementGuidId>b5ba0361-4d19-4c1e-9fbd-b83b0645de91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pin-input-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pin-input-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ebff56e4-14e1-4012-be0c-277d85d0946b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7092d085-8c47-4aa2-8221-161842472f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>otp__input_30CvO false</value>
      <webElementGuid>109ceb85-6d61-4399-ba63-293f8345d550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pin-input-0</value>
      <webElementGuid>f9fe8637-b774-459c-a3cc-54f64e0d5299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otp</value>
      <webElementGuid>b931993c-7682-40ff-9bf8-9792eafc599f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9.]+</value>
      <webElementGuid>37a6b49a-1aee-4e1e-935f-536b6746c725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>343c3fcb-32d7-4503-b781-f158995e27c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pin-input-0&quot;)</value>
      <webElementGuid>97511ece-7b90-477b-b652-a0d9f084b49d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pin-input-0']</value>
      <webElementGuid>706cc475-a381-4e17-8caf-83e0d0f8d951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>52d43312-e59e-42f2-be80-1d20deab1035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>c62e99bb-6430-4049-8e51-b922a9b4f00e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pin-input-0' and @name = 'otp' and @type = 'tel']</value>
      <webElementGuid>aabcacea-1803-4d16-aee9-774c263164c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
